/-
Copyright (c) 2026 Buxin Su. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Buxin Su
-/

import HighDimensionalProbability.Chapter9.Main
import HighDimensionalProbability.Chapter9.Exercise.Sec01
import HighDimensionalProbability.Chapter9.Exercise.Sec03

/-!
# Book Chapter 9 exercises attached to Section 9.4

Exercises 9.19, 9.20, 9.22, 9.23, 9.25, and 9.26 are used by the main
development and occur only in core.  Exercise 9.30 is a qualitative geometry
prompt and is skipped.  This file contains the ten non-load-bearing proof
atoms from Exercises 9.17, 9.18, 9.21, 9.24, and 9.27--9.29.
-/

open Matrix MeasureTheory ProbabilityTheory Set Filter InnerProductSpace
open scoped BigOperators ENNReal NNReal RealInnerProductSpace Topology
  Matrix.Norms.L2Operator

namespace HDP.Chapter9.Exercise

noncomputable section

/-- Coordinate `ℓ¹` norm.

**Lean implementation helper.** -/
def ellOneNorm {n : ℕ} (x : Euc n) : ℝ :=
  ∑ i, |x i|

/-- Number of nonzero coordinates.

**Lean implementation helper.** -/
def supportCard {n : ℕ} (x : Euc n) : ℕ :=
  (Finset.univ.filter fun i => x i ≠ 0).card

/-- `ell0` counts nonzero coordinates and defines sparsity. Predicate for an `s`-sparse vector.

**Book Equation (9.21).** -/
def IsSparse {n : ℕ} (s : ℕ) (x : Euc n) : Prop :=
  supportCard x ≤ s

/-- Best `s`-term approximation error in `ℓ¹`.

**Lean implementation helper.** -/
def bestSparseL1Error {n : ℕ} (s : ℕ) (x : Euc n) : ℝ :=
  sInf {r : ℝ | ∃ z : Euc n, IsSparse s z ∧ r = ellOneNorm (x - z)}

/-- Truncated `l1` ball. Unit `ℓ¹` ball truncated by the Euclidean unit ball.

**Book Equation (9.47), Exercise 9.25.** -/
def truncatedL1Ball (n s : ℕ) : Set (Euc n) :=
  {x | ellOneNorm x ≤ Real.sqrt s ∧ ‖x‖ ≤ 1}

/-- Unit `s`-sparse set. Euclidean-unit `s`-sparse vectors.

**Book Equation (9.46), Exercise 9.25.** -/
def sparseUnitSet (n s : ℕ) : Set (Euc n) :=
  {x | IsSparse s x ∧ ‖x‖ ≤ 1}

/-- Unit ball of a seminorm, used with a definiteness hypothesis below.

**Lean implementation helper.** -/
def seminormUnitBall {n : ℕ} (q : Seminorm ℝ (Euc n)) : Set (Euc n) :=
  {x | q x ≤ 1}

/-- Pointwise least-squares-plus-`ℓ¹` objective.

**Lean implementation helper.** -/
def lassoObjective {m n : ℕ}
    (A : Matrix (Fin m) (Fin n) ℝ) (y : Euc m)
    (lam : ℝ) (z : Euc n) : ℝ :=
  ‖y - matrixApply A z‖ ^ 2 + lam * ellOneNorm z

/-- Low-rank matrix measurements are Frobenius inner products. Frobenius measurement vector generated by a family of sensing matrices.

**Book Equation (9.25).** -/
def matrixMeasurements {m d₁ d₂ : ℕ}
    (A : Fin m → Matrix (Fin d₁) (Fin d₂) ℝ)
    (X : Matrix (Fin d₁) (Fin d₂) ℝ) : Euc m :=
  WithLp.toLp 2 (fun i => HDP.matrixFrobeniusInner (A i) X)

/-- Nuclear norm of a rectangular real matrix.

**Lean implementation helper.** -/
def rectangularNuclearNorm {d₁ d₂ : ℕ}
    (X : Matrix (Fin d₁) (Fin d₂) ℝ) : ℝ :=
  ∑ i : Fin (min d₁ d₂), HDP.matrixSingularValue X i

/-- Best rank-`r` nuclear-norm approximation error.

**Lean implementation helper.** -/
def bestRankNuclearError {d₁ d₂ : ℕ} (r : ℕ)
    (X : Matrix (Fin d₁) (Fin d₂) ℝ) : ℝ :=
  sInf {a : ℝ | ∃ Z : Matrix (Fin d₁) (Fin d₂) ℝ,
    HDP.matrixRank Z ≤ r ∧ a = rectangularNuclearNorm (X - Z)}

/-- Independent standard-Gaussian sensing matrices.

**Lean implementation helper.** -/
def IsGaussianMatrixMeasurementFamily {m d₁ d₂ : ℕ}
    {Ω : Type*} [MeasurableSpace Ω] (μ : Measure Ω)
    (A : Fin m → Ω → Matrix (Fin d₁) (Fin d₂) ℝ) : Prop :=
  (∀ i j k, HasLaw (fun ω => A i ω j k) (gaussianReal 0 1) μ) ∧
    iIndepFun (fun q : (Fin m × Fin d₁) × Fin d₂ =>
      fun ω => A q.1.1 ω q.1.2 q.2) μ

/-- **Exercise 9.17 (constrained recovery, mean squared error).** The source
prints only “extend” and no target bound. This is the quantitative square-
error endpoint obtained by integrating the same deviation tail.

**Book Exercise 9.17.** -/
theorem exercise_9_17 :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m n : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : HDP.RandomMatrix (Fin m) (Fin n) Ω)
        (T : Set (Euc n)) (x : Euc n) (xhat : Ω → Euc n) (K : ℝ),
        0 < m → 0 < n → x ∈ T → T.Nonempty → Bornology.IsBounded T →
        1 ≤ K → A.AEMeasurableEntries μ → A.IsotropicRows μ →
        iIndepFun (fun i ω => HDP.randomMatrixRow A i ω) μ →
        A.RowPsi2Bound μ K →
        (∀ ω, xhat ω ∈ T) →
        (∀ ω, matrixApply (A ω) (xhat ω) = matrixApply (A ω) x) →
        Measurable xhat → Integrable (fun ω => ‖xhat ω - x‖ ^ 2) μ →
        (∫ ω, ‖xhat ω - x‖ ^ 2 ∂μ) ≤
          C * K ^ 4 * setGaussianWidth T ^ 2 / m := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.17.
  sorry

/-- **Exercise 9.18 (recovery by norm minimization).** The seminorm is
assumed definite, and minimizer attainment is expressed pointwise rather than
hidden behind an `argmin`.

**Book Exercise 9.18.** -/
theorem exercise_9_18 :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m n : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : HDP.RandomMatrix (Fin m) (Fin n) Ω)
        (q : Seminorm ℝ (Euc n)) (x : Euc n)
        (xhat : Ω → Euc n) (K : ℝ),
        0 < m → 0 < n → (∀ z, q z = 0 → z = 0) → q x ≤ 1 →
        1 ≤ K → A.AEMeasurableEntries μ → A.IsotropicRows μ →
        iIndepFun (fun i ω => HDP.randomMatrixRow A i ω) μ →
        A.RowPsi2Bound μ K →
        (∀ ω, matrixApply (A ω) (xhat ω) = matrixApply (A ω) x) →
        (∀ ω z, matrixApply (A ω) z = matrixApply (A ω) x →
          q (xhat ω) ≤ q z) →
        Measurable xhat → Integrable (fun ω => ‖xhat ω - x‖) μ →
        (∫ ω, ‖xhat ω - x‖ ∂μ) ≤
          C * K ^ 2 * setGaussianWidth (seminormUnitBall q) /
            Real.sqrt m := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.18.
  sorry

/-- **Exercise 9.21 (Lasso).** The printed display drops the signal scale.
Here the homogeneous factor `‖x‖₂` is restored, the zero tuning denominator
is excluded explicitly, and possibly data-dependent noise is controlled by a
deterministic bound `η`.

**Book Exercise 9.21 (Lasso).** -/
theorem exercise_9_21 :
    ∃ c C : ℝ, 0 < c ∧ 0 < C ∧
      ∀ {m n s : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : HDP.RandomMatrix (Fin m) (Fin n) Ω)
        (x : Euc n) (w : Ω → Euc m) (xhat : Ω → Euc n)
        (K η lam : ℝ),
        0 < m → 2 ≤ n → 1 ≤ s → s ≤ n → IsSparse s x → x ≠ 0 →
        1 ≤ K → 0 ≤ η → 0 < lam →
        c * η ^ 2 / ellOneNorm x ≤ lam →
        lam ≤ C * η ^ 2 / ellOneNorm x →
        A.AEMeasurableEntries μ → A.IsotropicRows μ →
        iIndepFun (fun i ω => HDP.randomMatrixRow A i ω) μ →
        A.RowPsi2Bound μ K → (∀ ω, ‖w ω‖ ≤ η) →
        (∀ ω z,
          lassoObjective (A ω) (matrixApply (A ω) x + w ω) lam (xhat ω) ≤
            lassoObjective (A ω) (matrixApply (A ω) x + w ω) lam z) →
        Measurable xhat → Integrable (fun ω => ‖xhat ω - x‖) μ →
        (∫ ω, ‖xhat ω - x‖ ∂μ) ≤
          C * (K ^ 2 * Real.sqrt (s * Real.log n) * ‖x‖ + η) /
            Real.sqrt m := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.21.
  sorry

/-- **Exercise 9.24(a) (basis-pursuit recovery of a sparse signal).**.

**Book Exercise 9.24(a).** -/
theorem exercise_9_24_part_a :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m n s : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : HDP.RandomMatrix (Fin m) (Fin n) Ω)
        (x : Euc n) (xhat : Ω → Euc n) (K : ℝ),
        0 < m → 2 ≤ n → 1 ≤ s → s ≤ n → IsSparse s x → 1 ≤ K →
        A.AEMeasurableEntries μ → A.IsotropicRows μ →
        iIndepFun (fun i ω => HDP.randomMatrixRow A i ω) μ →
        A.RowPsi2Bound μ K →
        (∀ ω, matrixApply (A ω) (xhat ω) = matrixApply (A ω) x) →
        (∀ ω z, matrixApply (A ω) z = matrixApply (A ω) x →
          ellOneNorm (xhat ω) ≤ ellOneNorm z) →
        Measurable xhat → Integrable (fun ω => ‖xhat ω - x‖) μ →
        (∫ ω, ‖xhat ω - x‖ ∂μ) ≤
          C * K ^ 2 * Real.sqrt (s * Real.log n / m) * ‖x‖ := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.24(a).
  sorry

/-- **Exercise 9.24(b) (approximately sparse signal).** The source asks the
reader to state a guarantee; this declaration uses the standard best
`s`-term `ℓ¹` error and keeps the finite-sample term from part (a).

**Book Exercise 9.24(b).** -/
theorem exercise_9_24_part_b :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m n s : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : HDP.RandomMatrix (Fin m) (Fin n) Ω)
        (x : Euc n) (xhat : Ω → Euc n) (K : ℝ),
        0 < m → 2 ≤ n → 1 ≤ s → s ≤ n → 1 ≤ K →
        A.AEMeasurableEntries μ → A.IsotropicRows μ →
        iIndepFun (fun i ω => HDP.randomMatrixRow A i ω) μ →
        A.RowPsi2Bound μ K →
        (∀ ω, matrixApply (A ω) (xhat ω) = matrixApply (A ω) x) →
        (∀ ω z, matrixApply (A ω) z = matrixApply (A ω) x →
          ellOneNorm (xhat ω) ≤ ellOneNorm z) →
        Measurable xhat → Integrable (fun ω => ‖xhat ω - x‖) μ →
        (∫ ω, ‖xhat ω - x‖ ∂μ) ≤
          C * (K ^ 2 * Real.sqrt (s * Real.log
              (Real.exp 1 * n / s) / m) * ‖x‖ +
            bestSparseL1Error s x / Real.sqrt s) := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.24(b).
  sorry

/-- **Exercise 9.27 (Gaussian width of sparse vectors).** Both the sparse
set and its truncated convex surrogate receive the requested sharp two-sided
comparison, with universal constants and the valid range `1 ≤ s ≤ n`.

**Book Exercise 9.27.** -/
theorem exercise_9_27 :
    ∃ c C : ℝ, 0 < c ∧ 0 < C ∧
      ∀ {n s : ℕ}, 1 ≤ s → s ≤ n →
        let scale := Real.sqrt (s * Real.log (Real.exp 1 * n / s))
        c * scale ≤ setGaussianWidth (sparseUnitSet n s) ∧
        setGaussianWidth (sparseUnitSet n s) ≤ C * scale ∧
        c * scale ≤ setGaussianWidth (truncatedL1Ball n s) ∧
        setGaussianWidth (truncatedL1Ball n s) ≤ C * scale := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.27.
  sorry

/-- **Exercise 9.28 (Garnaev--Gluskin).** The source suppresses the random
subspace's dimension; `E` is here a Haar subspace of codimension `m`.

**Book Exercise 9.28.** -/
theorem exercise_9_28 :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m n : ℕ}, 0 < m → m < n → 2 ≤ n →
        Measurable (fun P : HDP.Chapter5.Grassmannian n (n - m) =>
          setDiameter (grassmannSection P (lpUnitBall n 1))) →
        Integrable (fun P : HDP.Chapter5.Grassmannian n (n - m) =>
          setDiameter (grassmannSection P (lpUnitBall n 1)))
            (HDP.Chapter5.grassmannHaarMeasure n (n - m)) →
        (∫ P, setDiameter (grassmannSection P (lpUnitBall n 1))
          ∂HDP.Chapter5.grassmannHaarMeasure n (n - m)) ≤
            C * Real.sqrt (Real.log (Real.exp 1 * n / m) / m) := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.28.
  sorry

/-- **Exercise 9.29(a) (nuclear-norm recovery program).**.

**Book Exercise 9.29(a).** -/
theorem exercise_9_29_part_a :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m d r : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : Fin m → Ω → Matrix (Fin d) (Fin d) ℝ)
        (X : Matrix (Fin d) (Fin d) ℝ)
        (Xhat : Ω → Matrix (Fin d) (Fin d) ℝ),
        0 < m → 0 < d → 1 ≤ r → r ≤ d → HDP.matrixRank X ≤ r →
        HDP.matrixFrobeniusNorm X ≤ 1 →
        IsGaussianMatrixMeasurementFamily μ A →
        (∀ ω, matrixMeasurements (fun i => A i ω) (Xhat ω) =
          matrixMeasurements (fun i => A i ω) X) →
        (∀ ω Z, matrixMeasurements (fun i => A i ω) Z =
            matrixMeasurements (fun i => A i ω) X →
          rectangularNuclearNorm (Xhat ω) ≤ rectangularNuclearNorm Z) →
        Measurable Xhat →
        Integrable (fun ω => HDP.matrixFrobeniusNorm (Xhat ω - X)) μ →
        (∫ ω, HDP.matrixFrobeniusNorm (Xhat ω - X) ∂μ) ≤
          C * Real.sqrt (r * d / m) := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.29(a).
  sorry

/-- **Exercise 9.29(b) (approximately low-rank matrices).** The approximation
term is the standard nuclear-norm tail divided by `√r`; a best Frobenius tail
would give a stronger statement that does not follow from the usual stable
low-rank recovery argument.

**Book Exercise 9.29(b).** -/
theorem exercise_9_29_part_b :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m d r : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : Fin m → Ω → Matrix (Fin d) (Fin d) ℝ)
        (X : Matrix (Fin d) (Fin d) ℝ)
        (Xhat : Ω → Matrix (Fin d) (Fin d) ℝ),
        0 < m → 0 < d → 1 ≤ r → r ≤ d →
        IsGaussianMatrixMeasurementFamily μ A →
        (∀ ω, matrixMeasurements (fun i => A i ω) (Xhat ω) =
          matrixMeasurements (fun i => A i ω) X) →
        (∀ ω Z, matrixMeasurements (fun i => A i ω) Z =
            matrixMeasurements (fun i => A i ω) X →
          rectangularNuclearNorm (Xhat ω) ≤ rectangularNuclearNorm Z) →
        Measurable Xhat →
        Integrable (fun ω => HDP.matrixFrobeniusNorm (Xhat ω - X)) μ →
        (∫ ω, HDP.matrixFrobeniusNorm (Xhat ω - X) ∂μ) ≤
          C * (Real.sqrt (r * d / m) * HDP.matrixFrobeniusNorm X +
            bestRankNuclearError r X / Real.sqrt r) := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.29(b).
  sorry

/-- **Exercise 9.29(c) (rectangular matrices).** The rate uses the correct
sum `d₁+d₂`, rather than silently identifying the two dimensions.

**Book Exercise 9.29(c).** -/
theorem exercise_9_29_part_c :
    ∃ C : ℝ, 0 < C ∧
      ∀ {m d₁ d₂ r : ℕ} {Ω : Type*} {mΩ : MeasurableSpace Ω}
        {μ : Measure Ω} [IsProbabilityMeasure μ]
        (A : Fin m → Ω → Matrix (Fin d₁) (Fin d₂) ℝ)
        (X : Matrix (Fin d₁) (Fin d₂) ℝ)
        (Xhat : Ω → Matrix (Fin d₁) (Fin d₂) ℝ),
        0 < m → 0 < d₁ → 0 < d₂ → 1 ≤ r → r ≤ min d₁ d₂ →
        HDP.matrixRank X ≤ r → HDP.matrixFrobeniusNorm X ≤ 1 →
        IsGaussianMatrixMeasurementFamily μ A →
        (∀ ω, matrixMeasurements (fun i => A i ω) (Xhat ω) =
          matrixMeasurements (fun i => A i ω) X) →
        (∀ ω Z, matrixMeasurements (fun i => A i ω) Z =
            matrixMeasurements (fun i => A i ω) X →
          rectangularNuclearNorm (Xhat ω) ≤ rectangularNuclearNorm Z) →
        Measurable Xhat →
        Integrable (fun ω => HDP.matrixFrobeniusNorm (Xhat ω - X)) μ →
        (∫ ω, HDP.matrixFrobeniusNorm (Xhat ω - X) ∂μ) ≤
          C * Real.sqrt (r * (d₁ + d₂) / m) := by
  -- EXERCISE-SORRY: Category A, non-load-bearing Exercise 9.29(c).
  sorry

end

end HDP.Chapter9.Exercise
