/-
Shared sphere-measure infrastructure for the formalization of Vershynin,
"High-Dimensional Probability" (2nd ed.).

The measure `unitSphereMeasure E` is the normalized surface-area measure on the
unit sphere of a nontrivial finite-dimensional real inner-product space.  The normalization
is built from Mathlib's polar-coordinate measure `volume.toSphere`.
-/
import Mathlib.MeasureTheory.Constructions.HaarToSphere
import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace
import Mathlib.MeasureTheory.Measure.Haar.NormedSpace
import Mathlib.Probability.ConditionalProbability
import Mathlib.Probability.Distributions.Gaussian.Multivariate
import Mathlib.Analysis.SpecialFunctions.Gaussian.FourierTransform
import Mathlib.MeasureTheory.Integral.Bochner.Set

open MeasureTheory ProbabilityTheory
open scoped ENNReal Pointwise

namespace HDP

noncomputable section

/-! ## Isometries of unit spheres -/

variable {E F : Type*}
  [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [NormedAddCommGroup F] [InnerProductSpace ℝ F]

/-- A linear isometry equivalence restricted to the unit spheres.

**Lean implementation helper.** -/
def unitSphereHomeomorph (f : E ≃ₗᵢ[ℝ] F) :
    Metric.sphere (0 : E) 1 ≃ₜ Metric.sphere (0 : F) 1 :=
  f.toHomeomorph.subtype fun x => by
    rw [mem_sphere_zero_iff_norm, mem_sphere_zero_iff_norm]
    change ‖x‖ = 1 ↔ ‖f x‖ = 1
    rw [f.norm_map]

/-- The unit-sphere homeomorphism induced by a linear isometry has the expected underlying-vector action.

**Lean implementation helper.** -/
@[simp]
theorem coe_unitSphereHomeomorph (f : E ≃ₗᵢ[ℝ] F)
    (x : Metric.sphere (0 : E) 1) :
    ((unitSphereHomeomorph f x : Metric.sphere (0 : F) 1) : F) = f x := rfl

/-- The inverse unit-sphere homeomorphism is induced by the inverse linear isometry.

**Lean implementation helper.** -/
@[simp]
theorem unitSphereHomeomorph_symm (f : E ≃ₗᵢ[ℝ] F) :
    (unitSphereHomeomorph f).symm = unitSphereHomeomorph f.symm := by
  ext x
  rfl

/-- The open cone of radii in `(0, 1)` generated by a subset of the unit sphere.

This is the region whose ambient volume defines Mathlib's `Measure.toSphere` on that subset.

**Lean implementation helper.** -/
def unitSphereSector (s : Set (Metric.sphere (0 : E) 1)) : Set E :=
  Set.Ioo (0 : ℝ) 1 • ((fun x : Metric.sphere (0 : E) 1 => (x : E)) '' s)

/-- A linear isometry carries the sector generated by a sphere set to the corresponding
sector. The preimage form is the one needed to transfer surface-area measures.

**Lean implementation helper.** -/
theorem preimage_unitSphereSector (f : E ≃ₗᵢ[ℝ] F)
    (s : Set (Metric.sphere (0 : F) 1)) :
    f ⁻¹' unitSphereSector s =
      unitSphereSector ((unitSphereHomeomorph f) ⁻¹' s) := by
  ext x
  constructor
  · intro hx
    rcases hx with ⟨r, hr, y, ⟨z, hzs, rfl⟩, hry⟩
    refine ⟨r, hr, (f.symm z : E), ?_, ?_⟩
    · refine ⟨unitSphereHomeomorph f.symm z, ?_, rfl⟩
      change unitSphereHomeomorph f (unitSphereHomeomorph f.symm z) ∈ s
      rw [← unitSphereHomeomorph_symm, (unitSphereHomeomorph f).apply_symm_apply]
      exact hzs
    · apply f.injective
      simpa using hry
  · intro hx
    rcases hx with ⟨r, hr, y, ⟨z, hzs, rfl⟩, hry⟩
    refine ⟨r, hr, f z, ?_, ?_⟩
    · exact ⟨unitSphereHomeomorph f z, hzs, rfl⟩
    · simpa using congrArg f hry

/-! ## Normalized surface-area measure -/

variable [MeasurableSpace E] [BorelSpace E] [FiniteDimensional ℝ E]
  [MeasurableSpace F] [BorelSpace F] [FiniteDimensional ℝ F]

/-- Surface area is invariant under linear isometry equivalences.

This fills the transport lemma not currently supplied directly by Mathlib for
`Measure.toSphere`; it follows from the sector formula and preservation of ambient volume.

**Lean implementation helper.** -/
theorem map_toSphere_unitSphereHomeomorph (f : E ≃ₗᵢ[ℝ] F) :
    Measure.map (unitSphereHomeomorph f) ((volume : Measure E).toSphere) =
      (volume : Measure F).toSphere := by
  ext s hs
  rw [Measure.map_apply (unitSphereHomeomorph f).measurable hs]
  rw [Measure.toSphere_apply' (volume : Measure E)
      (hs.preimage (unitSphereHomeomorph f).measurable)]
  rw [Measure.toSphere_apply' (volume : Measure F) hs]
  change Module.finrank ℝ E * (volume : Measure E)
      (unitSphereSector ((unitSphereHomeomorph f) ⁻¹' s)) =
    Module.finrank ℝ F * (volume : Measure F) (unitSphereSector s)
  rw [← preimage_unitSphereSector f s]
  rw [f.toLinearEquiv.finrank_eq]
  congr 1
  have hmp : MeasurePreserving f.toHomeomorph.toMeasurableEquiv
      (volume : Measure E) (volume : Measure F) := f.measurePreserving
  exact hmp.measure_preimage_equiv (unitSphereSector s)

/-- The normalized surface-area probability measure on the unit sphere of `E`.

For a zero-dimensional space the underlying surface measure is zero, so this definition is
still meaningful but not a probability measure. The probability instance below therefore
assumes `Nontrivial E`.

**Lean implementation helper.** -/
def unitSphereMeasure (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [MeasurableSpace E] [BorelSpace E] [FiniteDimensional ℝ E] :
    Measure (Metric.sphere (0 : E) 1) :=
  ProbabilityTheory.cond (volume.toSphere) Set.univ

instance instIsProbabilityMeasureUnitSphereMeasure [Nontrivial E] :
    IsProbabilityMeasure (unitSphereMeasure E) := by
  apply ProbabilityTheory.cond_isProbabilityMeasure
  rw [Measure.measure_univ_ne_zero]
  exact Measure.toSphere_ne_zero volume

/-- Normalized surface measure assigns mass one to the whole unit sphere.

**Lean implementation helper.** -/
@[simp]
theorem unitSphereMeasure_univ [Nontrivial E] :
    unitSphereMeasure E Set.univ = 1 := measure_univ

/-- Evaluation of normalized surface area as surface area divided by total surface area.

**Lean implementation helper.** -/
theorem unitSphereMeasure_apply [Nontrivial E]
    (s : Set (Metric.sphere (0 : E) 1)) :
    unitSphereMeasure E s =
      ((volume : Measure E).toSphere Set.univ)⁻¹ *
        (volume : Measure E).toSphere s := by
  simp [unitSphereMeasure, ProbabilityTheory.cond]

/-- Normalized surface area is invariant under every linear isometry equivalence.

**Lean implementation helper.** -/
theorem map_unitSphereMeasure (f : E ≃ₗᵢ[ℝ] F) :
    Measure.map (unitSphereHomeomorph f) (unitSphereMeasure E) =
      unitSphereMeasure F := by
  simp only [unitSphereMeasure, ProbabilityTheory.cond, Measure.restrict_univ]
  rw [Measure.map_smul, map_toSphere_unitSphereHomeomorph]
  have huniv := congrArg (fun μ : Measure (Metric.sphere (0 : F) 1) => μ Set.univ)
    (map_toSphere_unitSphereHomeomorph f)
  rw [Measure.map_apply (unitSphereHomeomorph f).measurable MeasurableSet.univ,
    Set.preimage_univ] at huniv
  rw [huniv]

/-- The sphere homeomorphism induced by a linear isometry equivalence is measure preserving
for normalized surface area.

**Lean implementation helper.** -/
theorem measurePreserving_unitSphereHomeomorph (f : E ≃ₗᵢ[ℝ] F) :
    MeasurePreserving (unitSphereHomeomorph f) (unitSphereMeasure E)
      (unitSphereMeasure F) :=
  ⟨(unitSphereHomeomorph f).measurable, map_unitSphereMeasure f⟩

/-! ## The direction of a standard Gaussian -/

open InnerProductSpace Filter
open scoped NNReal Topology ComplexConjugate RealInnerProductSpace

/-- The normalizing constant in the density proportional to
`exp (-‖x‖² / 2)` on a finite-dimensional real inner-product space.

**Lean implementation helper.** -/
def gaussianRadialNormalizer
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] : ℝ :=
  (Real.pi / (1 / 2 : ℝ)) ^ ((Module.finrank ℝ E : ℝ) / 2)

/-- The Gaussian radial normalizing constant is strictly positive.

**Lean implementation helper.** -/
lemma gaussianRadialNormalizer_pos
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] :
    0 < gaussianRadialNormalizer E := by
  dsimp [gaussianRadialNormalizer]
  positivity

/-- The radial Gaussian density, represented as a nonnegative real so it can
be used directly with `Measure.withDensity`.

**Lean implementation helper.** -/
def gaussianRadialDensity
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] (x : E) : ℝ≥0 :=
  Real.toNNReal ((gaussianRadialNormalizer E)⁻¹ *
    Real.exp (-(1 / 2 : ℝ) * ‖x‖ ^ 2))

/-- The real value of the Gaussian radial density is the normalized exponential of minus one half the squared norm.

**Lean implementation helper.** -/
lemma coe_gaussianRadialDensity
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] (x : E) :
    (gaussianRadialDensity E x : ℝ) =
      (gaussianRadialNormalizer E)⁻¹ *
        Real.exp (-(1 / 2 : ℝ) * ‖x‖ ^ 2) := by
  rw [gaussianRadialDensity, Real.coe_toNNReal]
  exact mul_nonneg (inv_nonneg.mpr (gaussianRadialNormalizer_pos E).le)
    (Real.exp_pos _).le

/-- The normalized radial Gaussian density is measurable on finite-dimensional Euclidean space.

**Lean implementation helper.** -/
lemma measurable_gaussianRadialDensity
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] :
    Measurable (gaussianRadialDensity E) := by
  change Measurable (fun x : E ↦ Real.toNNReal
    ((gaussianRadialNormalizer E)⁻¹ *
      Real.exp (-(1 / 2 : ℝ) * ‖x‖ ^ 2)))
  fun_prop

/-- The normalized radial Gaussian density integrates to one.

**Lean implementation helper.** -/
lemma integral_gaussianRadialDensity
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] :
    ∫ x : E, (gaussianRadialDensity E x : ℝ) = 1 := by
  simp_rw [coe_gaussianRadialDensity]
  rw [integral_const_mul]
  rw [GaussianFourier.integral_rexp_neg_mul_sq_norm
    (V := E) (by norm_num : 0 < (1 / 2 : ℝ))]
  exact inv_mul_cancel₀ (gaussianRadialNormalizer_pos E).ne'

/-- A radial presentation of the standard Gaussian. The characteristic
function argument below identifies it with Mathlib's `stdGaussian`.

**Lean implementation helper.** -/
def gaussianRadialMeasure
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] : Measure E :=
  volume.withDensity (fun x ↦ gaussianRadialDensity E x)

instance instIsProbabilityMeasureGaussianRadialMeasure
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] :
    IsProbabilityMeasure (gaussianRadialMeasure E) where
  measure_univ := by
    rw [gaussianRadialMeasure, withDensity_apply _ MeasurableSet.univ]
    rw [setLIntegral_univ]
    have hfun :
        (fun x : E ↦ ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞)) =
          fun x : E ↦ ENNReal.ofReal (gaussianRadialDensity E x : ℝ) := by
      funext x
      simp
    rw [hfun]
    rw [← ofReal_integral_eq_lintegral_ofReal]
    · rw [integral_gaussianRadialDensity]
      simp
    · exact integrable_of_integral_eq_one (integral_gaussianRadialDensity E)
    · exact ae_of_all _ (fun _ ↦ NNReal.coe_nonneg _)

/-- The characteristic function of the standard radial Gaussian measure is `exp (-‖t‖²/2)`.

**Lean implementation helper.** -/
lemma charFun_gaussianRadialMeasure
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] (t : E) :
    charFun (gaussianRadialMeasure E) t = Complex.exp (-‖t‖ ^ 2 / 2) := by
  rw [charFun_apply, gaussianRadialMeasure,
    integral_withDensity_eq_integral_smul (measurable_gaussianRadialDensity E)]
  simp only [NNReal.smul_def]
  have hfun :
      (fun x : E ↦ (gaussianRadialDensity E x : ℝ) •
          Complex.exp (inner ℝ x t * Complex.I)) =
        fun x : E ↦ ((gaussianRadialNormalizer E)⁻¹ : ℂ) *
          Complex.exp (-(1 / 2 : ℂ) * ‖x‖ ^ 2 + Complex.I * inner ℝ t x) := by
    funext x
    rw [coe_gaussianRadialDensity]
    simp only [Complex.real_smul]
    rw [Complex.ofReal_mul, Complex.ofReal_inv, Complex.ofReal_exp]
    push_cast
    rw [mul_assoc, ← Complex.exp_add]
    congr 2
    rw [real_inner_comm]
    ring
  rw [hfun, integral_const_mul]
  rw [GaussianFourier.integral_cexp_neg_mul_sq_norm_add
    (V := E) (b := (1 / 2 : ℂ)) (by norm_num) Complex.I t]
  have hnorm : ((gaussianRadialNormalizer E : ℝ) : ℂ) =
      ((Real.pi : ℂ) / (1 / 2 : ℂ)) ^
        ((Module.finrank ℝ E : ℂ) / 2) := by
    dsimp [gaussianRadialNormalizer]
    rw [Complex.ofReal_cpow (by positivity)]
    push_cast
    rfl
  rw [hnorm]
  field_simp
  congr 1
  simp [Complex.I_sq]
  ring

/-- The normalized radial Gaussian measure equals Mathlib's standard Gaussian measure.

**Lean implementation helper.** -/
theorem gaussianRadialMeasure_eq_stdGaussian
    (E : Type*) [NormedAddCommGroup E] [InnerProductSpace ℝ E]
    [FiniteDimensional ℝ E] [MeasurableSpace E] [BorelSpace E] :
    gaussianRadialMeasure E = stdGaussian E := by
  apply Measure.ext_of_charFun
  ext t
  rw [charFun_gaussianRadialMeasure, charFun_stdGaussian]

section GaussianDirection

variable [Nontrivial E]

/-- An arbitrary unit vector, used only to make Gaussian direction total at
the origin. A Gaussian hits that exceptional point with probability zero.

**Lean implementation helper.** -/
def defaultUnitDirection : Metric.sphere (0 : E) 1 :=
  Classical.choice (NormedSpace.sphere_nonempty_rclike (𝕜 := ℝ) (E := E) (by norm_num))

/-- The normalized direction `x / ‖x‖`, made total by assigning an arbitrary
unit vector at `x = 0`.

**Lean implementation helper.** -/
def gaussianDirection : E → Metric.sphere (0 : E) 1 :=
  Function.extend ((↑) : ({0}ᶜ : Set E) → E)
    (fun x ↦ (homeomorphUnitSphereProd E x).1)
    (fun _ ↦ defaultUnitDirection (E := E))

omit [MeasurableSpace E] [BorelSpace E] [FiniteDimensional ℝ E] in
/-- The underlying vector of a Gaussian direction is the original nonzero vector normalized by its norm.

**Lean implementation helper.** -/
lemma gaussianDirection_coe (x : ({0}ᶜ : Set E)) :
    gaussianDirection (E := E) x = (homeomorphUnitSphereProd E x).1 := by
  exact Function.extend_val_apply x.property

/-- Normalizing a nonzero vector, with the chosen default at zero, defines a measurable sphere-valued map.

**Lean implementation helper.** -/
lemma measurable_gaussianDirection : Measurable (gaussianDirection (E := E)) := by
  apply (MeasurableEmbedding.subtype_coe
    (measurableSet_singleton (0 : E)).compl).measurable_extend
  · fun_prop
  · exact measurable_const

/-- The Gaussian radius density is the radial Gaussian density restricted to positive radii and embedded in `ℝ≥0∞`.

**Lean implementation helper.** -/
def gaussianRadiusDensity (r : Set.Ioi (0 : ℝ)) : ℝ≥0∞ :=
  (Real.toNNReal ((gaussianRadialNormalizer E)⁻¹ *
    Real.exp (-(1 / 2 : ℝ) * r.1 ^ 2)) : ℝ≥0)

omit [MeasurableSpace E] [BorelSpace E] [Nontrivial E] in
/-- The Gaussian radius density is measurable on the positive real axis.

**Lean implementation helper.** -/
lemma measurable_gaussianRadiusDensity :
    Measurable (gaussianRadiusDensity (E := E)) := by
  change Measurable (fun r : Set.Ioi (0 : ℝ) ↦
    ((Real.toNNReal ((gaussianRadialNormalizer E)⁻¹ *
      Real.exp (-(1 / 2 : ℝ) * r.1 ^ 2)) : ℝ≥0) : ℝ≥0∞))
  fun_prop

omit [MeasurableSpace E] [BorelSpace E] [Nontrivial E] in
/-- At a nonzero vector, the radial Gaussian density equals the corresponding
positive-radius density.

**Lean implementation helper.** -/
lemma gaussianRadialDensity_eq_radiusDensity (x : ({0}ᶜ : Set E)) :
    ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞) =
      gaussianRadiusDensity (E := E) (homeomorphUnitSphereProd E x).2 := by
  rw [gaussianRadiusDensity, gaussianRadialDensity]
  congr 3
  rw [homeomorphUnitSphereProd_apply_snd_coe]

/-- The Gaussian mass of a directional preimage equals the corresponding spherical measure.

**Lean implementation helper.** -/
lemma gaussianRadialMeasure_preimage_direction
    (A : Set (Metric.sphere (0 : E) 1)) (hA : MeasurableSet A) :
    gaussianRadialMeasure E (gaussianDirection (E := E) ⁻¹' A) =
      (volume : Measure E).toSphere A *
        ∫⁻ r, gaussianRadiusDensity (E := E) r
          ∂Measure.volumeIoiPow (Module.finrank ℝ E - 1) := by
  let S : Set E := {0}ᶜ
  let T : Set S := (homeomorphUnitSphereProd E) ⁻¹' (A ×ˢ Set.univ)
  have hS : MeasurableSet S := (measurableSet_singleton (0 : E)).compl
  have hT : MeasurableSet T := (hA.prod MeasurableSet.univ).preimage
    (homeomorphUnitSphereProd E).measurable
  have himage : ((↑) : S → E) '' T =
      (gaussianDirection (E := E) ⁻¹' A) ∩ S := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩
      refine ⟨?_, y.property⟩
      change gaussianDirection (E := E) (y : E) ∈ A
      rw [gaussianDirection_coe (E := E) y]
      exact hy.1
    · rintro ⟨hxA, hxS⟩
      refine ⟨⟨x, hxS⟩, ?_, rfl⟩
      refine ⟨?_, Set.mem_univ _⟩
      change (homeomorphUnitSphereProd E ⟨x, hxS⟩).1 ∈ A
      rw [← gaussianDirection_coe (E := E) ⟨x, hxS⟩]
      exact hxA
  rw [gaussianRadialMeasure, withDensity_apply _
    (hA.preimage (measurable_gaussianDirection (E := E)))]
  have hne : ∀ᵐ x : E ∂(volume : Measure E), x ≠ 0 := by
    rw [ae_iff]
    simp
  have hnull : ∀ᵐ x ∂(volume : Measure E),
      x ∈ gaussianDirection (E := E) ⁻¹' A ↔
        x ∈ (gaussianDirection (E := E) ⁻¹' A) ∩ S := by
    filter_upwards [hne] with x hx0
    constructor
    · intro hx
      exact ⟨hx, by simpa [S] using hx0⟩
    · exact fun hx ↦ hx.1
  rw [setLIntegral_congr (eventuallyEq_set.2 hnull)]
  rw [← himage]
  rw [← setLIntegral_subtype hS T
    (fun x : E ↦ ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞))]
  have hpolar := (volume : Measure E).measurePreserving_homeomorphUnitSphereProd
  have hchange := hpolar.setLIntegral_comp_preimage_emb
    (homeomorphUnitSphereProd E).measurableEmbedding
    (fun p ↦ gaussianRadiusDensity (E := E) p.2) (A ×ˢ Set.univ)
  have hleft :
      (∫⁻ x in T, ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞)
          ∂((volume : Measure E).comap ((↑) : S → E))) =
        ∫⁻ x in T, gaussianRadiusDensity (E := E)
          (homeomorphUnitSphereProd E x).2
          ∂((volume : Measure E).comap ((↑) : S → E)) := by
    apply setLIntegral_congr_fun hT
    intro x _
    exact gaussianRadialDensity_eq_radiusDensity x
  rw [hleft, hchange]
  rw [← Measure.restrict_prod_eq_prod_univ A]
  change (∫⁻ b, (gaussianRadiusDensity (E := E) ∘ Prod.snd) b
      ∂((volume : Measure E).toSphere.restrict A).prod
        (Measure.volumeIoiPow (Module.finrank ℝ E - 1))) = _
  rw [lintegral_prod _
    ((measurable_gaussianRadiusDensity (E := E)).comp measurable_snd).aemeasurable]
  simp [mul_comm]

/-- Joint polar-coordinate formula for the radial Gaussian. Unlike the
direction-only formula above, this version retains an arbitrary measurable
condition on the radius. It is the measure-theoretic input to the genuine
independence statement for Gaussian length and direction.

**Lean implementation helper.** -/
lemma gaussianRadialMeasure_preimage_direction_inter_norm
    (A : Set (Metric.sphere (0 : E) 1)) (hA : MeasurableSet A)
    (B : Set ℝ) (hB : MeasurableSet B) :
    gaussianRadialMeasure E
        (gaussianDirection (E := E) ⁻¹' A ∩ (fun x : E ↦ ‖x‖) ⁻¹' B) =
      (volume : Measure E).toSphere A *
        ∫⁻ r in ((↑) : Set.Ioi (0 : ℝ) → ℝ) ⁻¹' B,
          gaussianRadiusDensity (E := E) r
            ∂Measure.volumeIoiPow (Module.finrank ℝ E - 1) := by
  let S : Set E := {0}ᶜ
  let R : Set (Set.Ioi (0 : ℝ)) := ((↑) : Set.Ioi (0 : ℝ) → ℝ) ⁻¹' B
  let T : Set S := (homeomorphUnitSphereProd E) ⁻¹' (A ×ˢ R)
  have hS : MeasurableSet S := (measurableSet_singleton (0 : E)).compl
  have hR : MeasurableSet R := hB.preimage measurable_subtype_coe
  have hT : MeasurableSet T := (hA.prod hR).preimage
    (homeomorphUnitSphereProd E).measurable
  have himage : ((↑) : S → E) '' T =
      (gaussianDirection (E := E) ⁻¹' A ∩ (fun x : E ↦ ‖x‖) ⁻¹' B) ∩ S := by
    ext x
    constructor
    · rintro ⟨y, hy, rfl⟩
      change (homeomorphUnitSphereProd E y).1 ∈ A ∧
        ((homeomorphUnitSphereProd E y).2 : ℝ) ∈ B at hy
      refine ⟨⟨?_, ?_⟩, y.property⟩
      · change gaussianDirection (E := E) (y : E) ∈ A
        rw [gaussianDirection_coe (E := E) y]
        exact hy.1
      · change ‖(y : E)‖ ∈ B
        simpa using hy.2
    · rintro ⟨⟨hxA, hxB⟩, hxS⟩
      refine ⟨⟨x, hxS⟩, ?_, rfl⟩
      refine ⟨?_, ?_⟩
      · change (homeomorphUnitSphereProd E ⟨x, hxS⟩).1 ∈ A
        rw [← gaussianDirection_coe (E := E) ⟨x, hxS⟩]
        exact hxA
      · change ((homeomorphUnitSphereProd E ⟨x, hxS⟩).2 : ℝ) ∈ B
        simpa using hxB
  rw [gaussianRadialMeasure, withDensity_apply _
    ((hA.preimage (measurable_gaussianDirection (E := E))).inter
      (hB.preimage measurable_norm))]
  have hne : ∀ᵐ x : E ∂(volume : Measure E), x ≠ 0 := by
    rw [ae_iff]
    simp
  have hnull : ∀ᵐ x ∂(volume : Measure E),
      x ∈ (gaussianDirection (E := E) ⁻¹' A ∩
          (fun x : E ↦ ‖x‖) ⁻¹' B) ↔
        x ∈ (gaussianDirection (E := E) ⁻¹' A ∩
          (fun x : E ↦ ‖x‖) ⁻¹' B) ∩ S := by
    filter_upwards [hne] with x hx0
    constructor
    · intro hx
      exact ⟨hx, by simpa [S] using hx0⟩
    · exact fun hx ↦ hx.1
  rw [setLIntegral_congr (eventuallyEq_set.2 hnull)]
  rw [← himage]
  rw [← setLIntegral_subtype hS T
    (fun x : E ↦ ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞))]
  have hpolar := (volume : Measure E).measurePreserving_homeomorphUnitSphereProd
  have hchange := hpolar.setLIntegral_comp_preimage_emb
    (homeomorphUnitSphereProd E).measurableEmbedding
    (fun p ↦ gaussianRadiusDensity (E := E) p.2) (A ×ˢ R)
  have hleft :
      (∫⁻ x in T, ((gaussianRadialDensity E x : ℝ≥0) : ℝ≥0∞)
          ∂((volume : Measure E).comap ((↑) : S → E))) =
        ∫⁻ x in T, gaussianRadiusDensity (E := E)
          (homeomorphUnitSphereProd E x).2
          ∂((volume : Measure E).comap ((↑) : S → E)) := by
    apply setLIntegral_congr_fun hT
    intro x _
    exact gaussianRadialDensity_eq_radiusDensity x
  rw [hleft, hchange]
  rw [← Measure.prod_restrict A R]
  change (∫⁻ b, (gaussianRadiusDensity (E := E) ∘ Prod.snd) b
      ∂((volume : Measure E).toSphere.restrict A).prod
        ((Measure.volumeIoiPow (Module.finrank ℝ E - 1)).restrict R)) = _
  rw [lintegral_prod _
    ((measurable_gaussianRadiusDensity (E := E)).comp measurable_snd).aemeasurable]
  simp [R, mul_comm]

/-- The total radial density mass is the reciprocal of the surface mass of the unit sphere.

**Lean implementation helper.** -/
lemma gaussianRadiusIntegral_eq_inv_sphereMass :
    (∫⁻ r, gaussianRadiusDensity (E := E) r
      ∂Measure.volumeIoiPow (Module.finrank ℝ E - 1)) =
        ((volume : Measure E).toSphere Set.univ)⁻¹ := by
  apply ENNReal.eq_inv_of_mul_eq_one_left
  have h := gaussianRadialMeasure_preimage_direction
    (E := E) Set.univ MeasurableSet.univ
  simpa [mul_comm] using h.symm

/-- Pushing the radial Gaussian measure through normalization gives the uniform measure on the unit sphere.

**Lean implementation helper.** -/
theorem map_gaussianDirection_radialMeasure :
    Measure.map (gaussianDirection (E := E)) (gaussianRadialMeasure E) =
      unitSphereMeasure E := by
  ext A hA
  rw [Measure.map_apply (measurable_gaussianDirection (E := E)) hA,
    gaussianRadialMeasure_preimage_direction A hA,
    gaussianRadiusIntegral_eq_inv_sphereMass, unitSphereMeasure_apply]
  ac_rfl

/-- For a radial standard Gaussian, direction and Euclidean length are
independent random variables. This is an actual `IndepFun` statement (and
therefore, by `IndepFun.map_prod_eq_prod_map_map`, an equality of the joint
law with the product of its marginals), not merely a marginal-law formula.

**Lean implementation helper.** -/
theorem indepFun_gaussianDirection_norm_radialMeasure :
    gaussianDirection (E := E) ⟂ᵢ[gaussianRadialMeasure E] (fun x : E ↦ ‖x‖) := by
  rw [indepFun_iff_measure_inter_preimage_eq_mul]
  intro A B hA hB
  rw [gaussianRadialMeasure_preimage_direction_inter_norm A hA B hB]
  rw [gaussianRadialMeasure_preimage_direction A hA]
  have hnorm := gaussianRadialMeasure_preimage_direction_inter_norm
    (E := E) Set.univ MeasurableSet.univ B hB
  simp only [Set.preimage_univ, Set.univ_inter] at hnorm
  rw [hnorm, gaussianRadiusIntegral_eq_inv_sphereMass]
  let M : ℝ≥0∞ := (volume : Measure E).toSphere Set.univ
  have hM0 : M ≠ 0 := by
    dsimp [M]
    exact Measure.measure_univ_ne_zero.mpr (Measure.toSphere_ne_zero volume)
  have hMtop : M ≠ ∞ := by
    exact ne_of_lt (measure_lt_top (volume : Measure E).toSphere Set.univ)
  let J : ℝ≥0∞ :=
    ∫⁻ r in ((↑) : Set.Ioi (0 : ℝ) → ℝ) ⁻¹' B,
      gaussianRadiusDensity (E := E) r
        ∂Measure.volumeIoiPow (Module.finrank ℝ E - 1)
  change (volume : Measure E).toSphere A * J =
    ((volume : Measure E).toSphere A * M⁻¹) * (M * J)
  calc
    (volume : Measure E).toSphere A * J =
        (volume : Measure E).toSphere A * ((M⁻¹ * M) * J) := by
      rw [ENNReal.inv_mul_cancel hM0 hMtop, one_mul]
    _ = ((volume : Measure E).toSphere A * M⁻¹) * (M * J) := by
      ac_rfl

/-- A standard
Gaussian vector's safe direction and Euclidean norm are independent. This is
the unique authoritative exercise endpoint; core code never imports an
exercise leaf.

**Book Exercise 3.22.** -/
theorem indepFun_gaussianDirection_norm_stdGaussian :
    gaussianDirection (E := E) ⟂ᵢ[stdGaussian E] (fun x : E ↦ ‖x‖) := by
  rw [← gaussianRadialMeasure_eq_stdGaussian E]
  exact indepFun_gaussianDirection_norm_radialMeasure (E := E)

/-- The joint law of Gaussian direction and length is the product of its
marginal laws.

**Book Exercise 3.22.** -/
theorem map_gaussianDirection_norm_stdGaussian :
    Measure.map (fun x : E ↦ (gaussianDirection (E := E) x, ‖x‖)) (stdGaussian E) =
      (Measure.map (gaussianDirection (E := E)) (stdGaussian E)).prod
        (Measure.map (fun x : E ↦ ‖x‖) (stdGaussian E)) := by
  exact (indepFun_gaussianDirection_norm_stdGaussian (E := E)).map_prod_eq_prod_map_map
    (measurable_gaussianDirection (E := E)).aemeasurable measurable_norm.aemeasurable

/-- The direction of a standard Gaussian vector is exactly uniform on the
unit sphere. No independence assertion is needed for this marginal law.

**Book Equation (3.15).** -/
theorem map_gaussianDirection_stdGaussian :
    Measure.map (gaussianDirection (E := E)) (stdGaussian E) =
      unitSphereMeasure E := by
  rw [← gaussianRadialMeasure_eq_stdGaussian E]
  exact map_gaussianDirection_radialMeasure (E := E)

end GaussianDirection

end
end HDP
